language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: build
      if: branch = main
      cache:
        directories:
          - node_modules
          - backend/node_modules
      install:
        # Install Serverless
        - npm install -g serverless

        # Install dependencies
        - cd backend
        - npm ci
        - cd -
      script:
        # Run tests
        - npm test
      after_success:
        - echo "ok"
