language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: build
      if: branch = main
      cache:
        directories:
          - node_modules
          - backend/node_modules
      install:
        # Install Serverless
        - npm install -g serverless

        # Install dependencies
        - cd backend
        - npm ci
        - cd -
      script:
        # Run tests
        - cd backend
        - npm test
        - cd -
      after_success:
        - sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile serverless -o
        - sls deploy -v
